### ISSUE TITLE
Big Background Dove 

### ISSUE THREAD

**Issue by alyciac** [ThadiusHukari/Abe-Keller-Peace-Education-Fund#3]
I guys! 

That big background dove is creating some unexpected issues when it comes to breakpoints.   

If I don't fix it we will have to update our breakpoints when it does get fixed.  I am going to futz with this and see if I can't get the overflow to hide correctly. 

Thanks!

**Comment by ThadiusHukari** [comment]
We could change the size and position? Then it doesn't have to be cropped.

Thadius Hukari 
thadiushukari@yahoo.com
541.308.5118

**Comment by alyciac** [comment]
I added width and I changed the left to a percentage and that seems to have fixed the background image and the overflow issue.
