### ISSUE TITLE
Sidebar About

### ISSUE THREAD

**Issue by alyciac** [ThadiusHukari/Abe-Keller-Peace-Education-Fund#5]
Adjust link text.   The Text on the sidebar gets bolder on hover (this is a wordpress default.) This is normally fine but it is causing the text and buttons to float down.  Not really an issue, but it is pretty annoying, if we get the chance it would be nice to update that.

**Comment by tazaccara** [comment]
Actually, that's not Wordpress default, that's on our styles sheet. I just
changed the font weight to normal on hover.

2016-12-08 10:54 GMT-08:00 Alycia Cahill <notifications@github.com>:

**Comment by alyciac** [comment]
Thanks!
